version: '3'

services:
  seata-server:
    image: seataio/seata-server:1.1.0
    container_name: seata-server
    #hostname: seata-server
    # ports:
      # - 8091:8091
    # expose:
      # - 8091 
    environment:
      - SEATA_IP=127.0.0.1
      - SEATA_PORT=8091
      - SEATA_CONFIG_NAME=file:/seata-server/resources/registry
    volumes:
      - ./conf:/seata-server/resources
      - ./logs:/seata-server/logs
    network_mode: "host"
    deploy:
        resources:
            limits:
                cpus: '2'
                memory: 128m