echo
@start docker exec -d jd_scripts /bin/sh -c "find /scripts/logs -name '*.log' | grep -v 'sharecodeCollection' | xargs rm -rf"
choice /t 2 /d y /n >nul
@start docker exec -d jd_scripts /bin/sh -c "node /scripts/jd_bean_change.js |ts >> /scripts/logs/jd_bean_change.log;node /scripts/jd_bean_home.js |ts >> /scripts/logs/jd_bean_home.log;node /scripts/jd_bean_sign.js |ts >> /scripts/logs/jd_bean_sign.log;node /scripts/jd_beauty.js |ts >> /scripts/logs/jd_beauty.log;node /scripts/jd_blueCoin.js |ts >> /scripts/logs/jd_blueCoin.log;node /scripts/jd_bookshop.js |ts >> /scripts/logs/jd_bookshop.log;node /scripts/jd_car.js |ts >> /scripts/logs/jd_car.log;node /scripts/jd_car_exchange.js |ts >> /scripts/logs/jd_car_exchange.log;"
@start docker exec -d jd_scripts /bin/sh -c "node /scripts/jd_carnivalcity.js |ts >> /scripts/logs/jd_carnivalcity.log;node /scripts/jd_cash.js |ts >> /scripts/logs/jd_cash.log;node /scripts/jd_cfd.js |ts >> /scripts/logs/jd_cfd.log;node /scripts/jd_club_lottery.js |ts >> /scripts/logs/jd_club_lottery.log;node /scripts/jd_crazy_joy.js |ts >> /scripts/logs/jd_crazy_joy.log;node /scripts/jd_crazy_joy_bonus.js |ts >> /scripts/logs/jd_crazy_joy_bonus.log;node /scripts/jd_daily_egg.js |ts >> /scripts/logs/jd_daily_egg.log;"
@start docker exec -d jd_scripts /bin/sh -c "node /scripts/jd_dreamFactory.js |ts >> /scripts/logs/jd_dreamFactory.log;node /scripts/jd_family.js |ts >> /scripts/logs/jd_family.log;node /scripts/jd_fruit.js |ts >> /scripts/logs/jd_fruit.log;node /scripts/jd_get_share_code.js |ts >> /scripts/logs/jd_get_share_code.log;node /scripts/jd_jdfactory.js |ts >> /scripts/logs/jd_jdfactory.log;node /scripts/jd_jdzz.js |ts >> /scripts/logs/jd_jdzz.log;node /scripts/jd_joy.js |ts >> /scripts/logs/jd_joy.log;node /scripts/jd_joy_feedPets.js |ts >> /scripts/logs/jd_joy_feedPets.log;"
@start docker exec -d jd_scripts /bin/sh -c "node /scripts/jd_joy_reward.js |ts >> /scripts/logs/jd_joy_reward.log;node /scripts/jd_joy_run.js |ts >> /scripts/logs/jd_joy_run.log;node /scripts/jd_jxd.js |ts >> /scripts/logs/jd_jxd.log;node /scripts/jd_jxnc.js |ts >> /scripts/logs/jd_jxnc.log;node /scripts/jd_kd.js |ts >> /scripts/logs/jd_kd.log;node /scripts/jd_live.js |ts >> /scripts/logs/jd_live.log;node /scripts/jd_live_redrain.js |ts >> /scripts/logs/jd_live_redrain.log;node /scripts/jd_lotteryMachine.js |ts >> /scripts/logs/jd_lotteryMachine.log;"
@start docker exec -d jd_scripts /bin/sh -c "node /scripts/jd_mohe.js |ts >> /scripts/logs/jd_mohe.log;node /scripts/jd_moneyTree.js |ts >> /scripts/logs/jd_moneyTree.log;node /scripts/jd_ms.js |ts >> /scripts/logs/jd_ms.log;node /scripts/jd_necklace.js |ts >> /scripts/logs/jd_necklace.log;node /scripts/jd_nzmh.js |ts >> /scripts/logs/jd_nzmh.log;node /scripts/jd_pet.js |ts >> /scripts/logs/jd_pet.log;node /scripts/jd_pigPet.js |ts >> /scripts/logs/jd_pigPet.log;node /scripts/jd_plantBean.js |ts >> /scripts/logs/jd_plantBean.log;node /scripts/jd_price.js |ts >> /scripts/logs/jd_price.log;"
@start docker exec -d jd_scripts /bin/sh -c "node /scripts/jd_rankingList.js |ts >> /scripts/logs/jd_rankingList.log;node /scripts/jd_redPacket.js |ts >> /scripts/logs/jd_redPacket.log;node /scripts/jd_sgmh.js |ts >> /scripts/logs/jd_sgmh.log;node /scripts/jd_shop.js |ts >> /scripts/logs/jd_shop.log;node /scripts/jd_small_home.js |ts >> /scripts/logs/jd_small_home.log;node /scripts/jd_speed.js |ts >> /scripts/logs/jd_speed.log;node /scripts/jd_speed_redpocke.js |ts >> /scripts/logs/jd_speed_redpocke.log;node /scripts/jd_speed_sign.js |ts >> /scripts/logs/jd_speed_sign.log;"
@start docker exec -d jd_scripts /bin/sh -c "node /scripts/jd_superMarket.js |ts >> /scripts/logs/jd_superMarket.log;node /scripts/jd_syj.js |ts >> /scripts/logs/jd_syj.log;node /scripts/jx_sign.js |ts >> /scripts/logs/jx_sign.log;node /scripts/jd_unsubscribe.js |ts >> /scripts/logs/jd_unsubscribe.log;"
pause
