version: '2'
networks:
  sentinel-master:
    driver: bridge
    ipam:
      config:
      -
        subnet: 172.100.0.0/16
        gateway: 172.100.0.1
services:
    master:
        image: redis
        container_name: redis
        ports:
          - "6379:6379"
        restart: always
        expose:
            - 6379
        volumes:
          - ./conf/redis.conf:/etc/redis/redis.conf
        command: /bin/bash -c "redis-server /etc/redis/redis.conf --port 6379"
        networks:
          sentinel-master:
            ipv4_address: 172.100.0.10
    redis1:
        image: redis
        container_name: redis1
        ports:
          - "6380:6379"
        restart: always
        expose:
            - 6379
        volumes:
          - ./conf/redis.conf:/etc/redis/redis.conf
        command: /bin/bash -c "sleep 2 && redis-server /etc/redis/redis.conf"
        networks:
          sentinel-master:
            ipv4_address: 172.100.0.11
    redis2:
        image: redis
        container_name: redis2
        ports:
          - "6390:6379"
        restart: always
        expose:
            - 6379
        volumes:
          - ./conf/redis.conf:/etc/redis/redis.conf
        command: /bin/bash -c "sleep 2 && redis-server /etc/redis/redis.conf"
        networks:
          sentinel-master:
            ipv4_address: 172.100.0.12
    redis3:
        image: redis
        container_name: redis3
        ports:
          - "6381:6379"
        restart: always
        expose:
            - 6379
        volumes:
          - ./conf/redis.conf:/etc/redis/redis.conf
        command: /bin/bash -c "sleep 2 && redis-server /etc/redis/redis.conf"
        networks:
          sentinel-master:
            ipv4_address: 172.100.0.13
    redis4:
        image: redis
        container_name: redis4
        ports:
          - "6391:6379"
        restart: always
        expose:
            - 6379
        volumes:
          - ./conf/redis.conf:/etc/redis/redis.conf
        command: /bin/bash -c "sleep 2 && redis-server /etc/redis/redis.conf"
        networks:
          sentinel-master:
            ipv4_address: 172.100.0.14
    redis5:
        image: redis
        container_name: redis5
        ports:
          - "6382:6379"
        restart: always
        expose:
            - 6379
        volumes:
          - ./conf/redis.conf:/etc/redis/redis.conf
        command: /bin/bash -c "sleep 2 && redis-server /etc/redis/redis.conf"
        networks:
          sentinel-master:
            ipv4_address: 172.100.0.15
    redis6:
        image: redis
        container_name: redis6
        ports:
          - "6392:6379"
        restart: always
        expose:
            - 6379
        volumes:
          - ./conf/redis.conf:/etc/redis/redis.conf
        command: /bin/bash -c "sleep 2 && redis-server /etc/redis/redis.conf"
        networks:
          sentinel-master:
            ipv4_address: 172.100.0.16
