spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: phonemall-search
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  thymeleaf:
    cache: false
server:
  port: 12000
logging:
  level:
    com.city: debug
