version: '2'
services:
    nacos:
        image: nacos/nacos-server:2.0.1
        container_name: nacos
        hostname: nacos
        # privileged: true
        ports:
          - "8848:8848"
          - "9555:9555"
        volumes:
          - ./logs:/home/nacos/logs
        environment:                        # 设置环境变量,相当于docker run命令中的-e
          - PREFER_HOST_MODE=hostname                 # 如果支持主机名可以使用hostname,否则使用ip，默认也是ip
          - MODE=standalone                           # 单机模式启动
          - SPRING_DATASOURCE_PLATFORM=mysql          # 数据源平台 仅支持mysql或不保存empty
          - MYSQL_SERVICE_HOST=mysql    # 注：这里不能为`127.0.0.1`或`localhost`方式！！！
          - MYSQL_SERVICE_DB_NAME=nacos_config        # 所需sql脚本位于 `nacos-mysql/nacos-mysql.sql`
          - MYSQL_SERVICE_PORT=3306
          - MYSQL_SERVICE_USER=root
          - MYSQL_SERVICE_PASSWORD=root
          # JVM调优参数
          - JVM_XMS=128m   #-Xms default :2g
          - JVM_XMX=128m   #-Xmx default :2g
          - JVM_XMN=64m   #-Xmn default :1g
          - JVM_MS=16m     #-XX:MetaspaceSize default :128m
          - JVM_MMS=32m    #-XX:MaxMetaspaceSize default :320m
          - NACOS_DEBUG=n #是否开启远程debug，y/n，默认n
          - TOMCAT_ACCESSLOG_ENABLED=false #是否开始tomcat访问日志的记录，默认false
        networks:
          myNetwork:
            ipv4_address: 172.100.0.20
        mem_limit: 512m   # 最大使用内存
        # deploy:
           # resources:
              # limits:
                 # cpus: '2'
                 # memory: 512m
networks:
  myNetwork:   #自定义网络名称
    external:     #外部已定义网卡
      name: "myNetwork"    #使用docker-compose的默认网卡　　
