version: "2"
services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    privileged: true
    restart: always
    volumes:
      - ./jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
