spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: product_route
          uri: lb://phonemall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: coupon_route
          uri: lb://phonemall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: third_party_route
          uri: lb://phonemall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>/?.*),/$\{segment}

        - id: member_route
          uri: lb://phonemall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: ware_route
          uri: lb://phonemall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: order_route
          uri: lb://phonemall-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}
        - id: admin_route
          uri: lb://phonemall-admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /phonemall-admin/$\{segment}
        - id: phonemall_host_route
          uri: lb://phonemall-product
          predicates:
            - Host=phonemall.com,item.phonemall.com

        - id: phonemall_search_route
          uri: lb://phonemall-search
          predicates:
            - Host=search.phonemall.com

        - id: phonemall_auth_route
          uri: lb://phonemall-auth-server
          predicates:
            - Host=auth.phonemall.com

        - id: phonemall_cart_route
          uri: lb://phonemall-cart
          predicates:
            - Host=cart.phonemall.com

        - id: phonemall_order_route
          uri: lb://phonemall-order
          predicates:
            - Host=order.phonemall.com

        - id: phonemall_member_route
          uri: lb://phonemall-member
          predicates:
            - Host=member.phonemall.com

        - id: phonemall_seckill_route
          uri: lb://phonemall-seckill
          predicates:
            - Host=seckill.phonemall.com

  application:
    name: phonemall-gateway
server:
  port: 88
