spring:
  datasource:
    url: jdbc:mysql://localhost:3306/phonemall_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: phonemall
    password: phonemall
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: phonemall-coupon
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      #逻辑删除
      logic-delete-value: 0
      logic-not-delete-value: 1
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 7000
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
